import React, { useState } from 'react';
import { Copy, Check, Download, Volume2, VolumeX, Sparkles, BookOpen, Tag, Layers, List } from 'lucide-react';
import { StudyPack } from '../types';
import { ScrollStack, ScrollStackItem } from './react-bits/ScrollStack';

interface SummaryTabProps {
  studyPack: StudyPack;
  documentTitle?: string;
}

export const SummaryTab: React.FC<SummaryTabProps> = ({ studyPack, documentTitle }) => {
  const [copied, setCopied] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [viewMode, setViewMode] = useState<'list' | 'stack'>('list');

  const handleCopy = async () => {
    const textToCopy = `# ${studyPack.title || documentTitle || 'Study Summary'}\n\n` +
      `## Key Takeaways (5-Point Summary):\n` +
      studyPack.summary.map((b, i) => `${i + 1}. ${b}`).join('\n\n') +
      (studyPack.keyTerms && studyPack.keyTerms.length > 0
        ? `\n\n## Key Vocabulary:\n` +
          studyPack.keyTerms.map((t) => `- **${t.term}**: ${t.definition}`).join('\n')
        : '');

    await navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const markdownContent = `# ${studyPack.title || documentTitle || 'Study Summary'}\n\n` +
      `Generated by Study Buddy on ${new Date().toLocaleDateString()}\n\n` +
      `## 5-Point Summary\n` +
      studyPack.summary.map((b, i) => `${i + 1}. ${b}`).join('\n\n') +
      (studyPack.keyTerms && studyPack.keyTerms.length > 0
        ? `\n\n## Key Terms & Concepts\n` +
          studyPack.keyTerms.map((t) => `- **${t.term}**: ${t.definition}`).join('\n')
        : '');

    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${(studyPack.title || 'study-summary').toLowerCase().replace(/\s+/g, '-')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const toggleSpeech = () => {
    if (!('speechSynthesis' in window)) return;

    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
    } else {
      window.speechSynthesis.cancel();
      const textToRead = `${studyPack.title || 'Study Summary'}. Key points: ` +
        studyPack.summary.map((b, i) => `Point ${i + 1}: ${b}`).join('. ');
      const utterance = new SpeechSynthesisUtterance(textToRead);
      utterance.rate = 1.0;
      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = () => setIsSpeaking(false);
      window.speechSynthesis.speak(utterance);
      setIsSpeaking(true);
    }
  };

  return (
    <div className="space-y-8 animate-fadeIn">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-indigo-500/15 via-purple-500/15 to-pink-500/15 dark:from-[#18123c] dark:via-[#1e164c] dark:to-[#18123c] rounded-3xl p-6 sm:p-8 border-2 border-indigo-200/80 dark:border-indigo-800/60 shadow-xl backdrop-blur-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="space-y-1.5">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-black bg-gradient-to-r from-indigo-500/20 to-purple-500/20 text-indigo-700 dark:text-indigo-300 border border-indigo-300/50">
              <Sparkles className="w-3.5 h-3.5 text-indigo-500" />
              <span>5-Bullet Core Distillation</span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-black text-slate-900 dark:text-white tracking-tight">
              {studyPack.title || 'Executive Study Summary'}
            </h2>
            <p className="text-xs sm:text-sm text-slate-600 dark:text-slate-300 font-medium">
              Essential concepts extracted directly from your study material.
            </p>
          </div>

          <div className="flex items-center flex-wrap gap-2.5">
            {/* View Mode Toggle: List vs Stack */}
            <div className="inline-flex p-1 rounded-2xl bg-white dark:bg-[#1f174e] border-2 border-indigo-100 dark:border-indigo-800 shadow-sm">
              <button
                onClick={() => setViewMode('list')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-black transition-all ${
                  viewMode === 'list'
                    ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-xs'
                    : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                }`}
                title="Standard List View"
              >
                <List className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">List</span>
              </button>
              <button
                onClick={() => setViewMode('stack')}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-black transition-all ${
                  viewMode === 'stack'
                    ? 'bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-xs'
                    : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
                }`}
                title="ScrollStack View"
              >
                <Layers className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">ScrollStack</span>
              </button>
            </div>

            {'speechSynthesis' in window && (
              <button
                onClick={toggleSpeech}
                className={`inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold transition-all border-2 ${
                  isSpeaking
                    ? 'bg-rose-50 border-rose-300 text-rose-700 dark:bg-rose-950 dark:border-rose-700 dark:text-rose-200 animate-pulse'
                    : 'bg-white dark:bg-[#1a1442] border-indigo-200/80 dark:border-indigo-800/80 text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-[#231b56] shadow-sm'
                }`}
                title={isSpeaking ? 'Stop Audio' : 'Listen to Summary'}
              >
                {isSpeaking ? <VolumeX className="w-4 h-4 text-rose-500" /> : <Volume2 className="w-4 h-4 text-indigo-500" />}
                <span>{isSpeaking ? 'Stop' : 'Listen'}</span>
              </button>
            )}

            <button
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold bg-white dark:bg-[#1a1442] border-2 border-indigo-200/80 dark:border-indigo-800/80 text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-[#231b56] shadow-sm transition-all"
              title="Copy markdown to clipboard"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 text-emerald-500" />
                  <span className="text-emerald-600 dark:text-emerald-400 font-extrabold">Copied!</span>
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 text-indigo-500" />
                  <span>Copy</span>
                </>
              )}
            </button>

            <button
              onClick={handleDownload}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold bg-white dark:bg-[#1a1442] border-2 border-indigo-200/80 dark:border-indigo-800/80 text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-[#231b56] shadow-sm transition-all"
              title="Download Markdown summary"
            >
              <Download className="w-4 h-4 text-purple-500" />
              <span>Export .md</span>
            </button>
          </div>
        </div>
      </div>

      {/* 5-Bullet Points Container: EITHER List OR ScrollStack */}
      {viewMode === 'list' ? (
        <div className="space-y-4">
          <h3 className="text-xs font-black tracking-wider text-indigo-600 dark:text-indigo-400 uppercase flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-indigo-500" />
            <span>Key Insights ({studyPack.summary.length} Core Bullets)</span>
          </h3>

          <div className="grid gap-4">
            {studyPack.summary.map((bullet, idx) => (
              <div
                key={idx}
                className="group relative flex items-start gap-4 p-5 rounded-3xl bg-white dark:bg-[#150f33] border-2 border-indigo-100 dark:border-indigo-900/60 hover:border-indigo-400 dark:hover:border-indigo-500 shadow-md hover:shadow-xl transition-all duration-200"
              >
                <div className="flex-shrink-0 w-9 h-9 rounded-2xl bg-gradient-to-br from-indigo-500 via-purple-600 to-pink-500 text-white font-black text-sm flex items-center justify-center shadow-md shadow-indigo-500/25 group-hover:scale-105 transition-transform">
                  {idx + 1}
                </div>
                <div className="flex-1 pt-0.5">
                  <p className="text-slate-900 dark:text-slate-100 leading-relaxed font-semibold text-base">
                    {bullet}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      ) : (
        /* SCROLLSTACK VIEW */
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-black tracking-wider text-indigo-600 dark:text-indigo-400 uppercase flex items-center gap-2">
              <Layers className="w-4 h-4 text-indigo-500" />
              <span>Lenis Smooth ScrollStack &bull; 5 Summary Cards</span>
            </h3>
            <span className="text-xs font-semibold text-slate-500 dark:text-slate-400">
              Scroll down inside to stack
            </span>
          </div>

          <div className="h-[480px] rounded-3xl overflow-hidden border-2 border-indigo-200/80 dark:border-indigo-800/80 bg-slate-900 shadow-2xl">
            <ScrollStack
              itemDistance={40}
              itemScale={0.035}
              itemStackDistance={24}
              stackPosition="12%"
              scaleEndPosition="5%"
              baseScale={0.9}
              blurAmount={1}
              className="h-full"
            >
              {studyPack.summary.map((bullet, idx) => (
                <ScrollStackItem
                  key={idx}
                  itemClassName="bg-gradient-to-br from-[#1b1442] to-[#120d2e] border-2 border-indigo-500/30 shadow-2xl text-white"
                >
                  <div className="space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="px-3 py-1 rounded-full text-xs font-black bg-gradient-to-r from-indigo-500/30 to-purple-500/30 text-indigo-300 border border-indigo-400/30">
                        Takeaway #{idx + 1} of {studyPack.summary.length}
                      </span>
                      <span className="text-xs font-bold text-indigo-300">Core Insight</span>
                    </div>
                    <p className="text-base sm:text-lg font-bold leading-relaxed text-slate-100">
                      {bullet}
                    </p>
                  </div>
                </ScrollStackItem>
              ))}
            </ScrollStack>
          </div>
        </div>
      )}

      {/* Key Terms / Vocabulary (if provided) */}
      {studyPack.keyTerms && studyPack.keyTerms.length > 0 && (
        <div className="space-y-4 pt-4 border-t-2 border-indigo-100 dark:border-indigo-950">
          <h3 className="text-xs font-black tracking-wider text-purple-600 dark:text-purple-400 uppercase flex items-center gap-2">
            <Tag className="w-4 h-4 text-purple-500" />
            <span>Essential Terminology & Definitions</span>
          </h3>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {studyPack.keyTerms.map((item, i) => (
              <div
                key={i}
                className="p-4 rounded-2xl bg-white dark:bg-[#150f33] border-2 border-indigo-100 dark:border-indigo-900/60 hover:border-purple-400 transition-all shadow-sm"
              >
                <span className="text-xs font-black text-indigo-600 dark:text-indigo-400 block mb-1">
                  {item.term}
                </span>
                <p className="text-xs sm:text-sm text-slate-700 dark:text-slate-300 leading-normal font-medium">
                  {item.definition}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
